# Generated by Django 4.0 on 2022-01-03 11:13

from django.db import migrations

from accounts.models import User


def gen_master(apps, schema_editor):
    User.objects.create_user(username="admin", password="admin", first_name="관리자", email="", gender="F",
                             is_superuser=True, is_staff=True)

    for id in range(2, 5):
        username = f"user{id}"
        password = f"user{id}"
        first_name = f"이름{id}"
        email = f"test{id}@test.com"
        gender = 'M'

        User.objects.create_user(username=username, password=password, first_name=first_name,
                                 email=email, gender=gender)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_provider_accounts_id_user_provider_type_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatar',
        ),

        migrations.RunPython(gen_master),
    ]
