# Generated by Django 4.0 on 2022-01-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_avarar_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider_type_code',
            field=models.CharField(choices=[('local', '로컬'), ('kakao', '카카오')], default='local', max_length=20, verbose_name='프로바이더 타입코드'),
        ),
    ]
